### ISSUE TITLE
Something wrong with commas @carolsinc

### ISSUE THREAD

**Issue by adrianna16** [adrianna16/fancy-hover-boxes#1]
hi, markbot is telling me there is something wrong with my commas but from what it looks like I have everything the same. also my images overlap each other and I do not know why @carolsinc

**Comment by carolsinc** [comment]
Set your img in css to width 100% and display block

**Comment by carolsinc** [comment]
Does markbot give you a line of code about the commas? I'm not seeing anything, but stuff like commas can be tricky to spot

**Comment by adrianna16** [comment]
its giving me this
________________________________

**Comment by carolsinc** [comment]
Can you send me a screen shot of markbot?

**Comment by adrianna16** [comment]
nevermind i figured it out, however im still having problems with the images they are still over lapping no matter what  do
________________________________

**Comment by carolsinc** [comment]
did you add width 100% and display block to your images? If you have make sure you push it, it's not showing up in your css file
